baseURL = 'https://tedthetrumpet.github.io/'
# baseURL = 'https://tedthetrumpet.github.io/jsvdw_hugo/'
languageCode = 'en-us'
title = 'JSvdW Hugo test'
# theme = 'hugo-book'
theme = 'jsvdw'
# suggestion to fix image
# fixes image on ghub, but breaks layout!
# canonifyURLs = true